services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./user-service
    image: arac_kiralama_user_service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGO_URI: mongodb://mongo:27017/user_db
      JWT_SECRET: super_gizli_anahtar_kelimem_123
    depends_on:
      - mongo
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "user-service"}]'

  vehicle-service:
    build: ./vehicle-service
    image: arac_kiralama_vehicle_service
    container_name: vehicle-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      MONGO_URI: mongodb://mongo:27017/vehicle_db
    depends_on:
      - mongo
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "vehicle-service"}]'

  rental-service:
    build: ./rental-service
    image: arac_kiralama_rental_service
    container_name: rental-service
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      MONGO_URI: mongodb://mongo:27017/rental_db
      JWT_SECRET: super_gizli_anahtar_kelimem_123 
      VEHICLE_SERVICE_URL: http://vehicle-service:3002/api/vehicles
    depends_on:
      - mongo
      - vehicle-service 
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "rental-service"}]'

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_server
    user: root 
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 

  # --- DATADOG AJANI BURADAN BAŞLIYOR ---
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog_agent
    environment:
      - DD_API_KEY=b7639f20ef276502e65aa9420f6efadf # <-- Kendi anahtarını buraya koy
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

volumes:
  mongo_data:
  jenkins_data: